content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ title, date, draft, tags ]
      layout: tree
      node:
        filename: index.md
        hideDirs: nodes
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
      - name: body
        label: Body
        type: rich-text
  - name: about
    label: About
    type: file
    path: 'content/about/index.md'
    view:
      fields: [ title, date, draft ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text