baseURL: https://blog.haicon.moe
languageCode: en-us
title: /home/jackblk
theme: hello-friend
pagination:
  pagerSize: 5

params:
  showReadingTime: true
  contentTypeName: posts
  defaultTheme: dark

taxonomies:
  tag: tags

enableGitInfo: true

languages:
  en:
    params:
      logo:
        logoText: /home/jackblk 🐈
        logoHomeLink: /

    menuMore: Show more
    writtenBy: Written by
    readMore: Read more
    # readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02
    lastModDisplay: "Modified:"

    menu:
      main:
        - identifier: about
          name: about
          url: /about/
        - identifier: tags
          name: tags
          url: /tags/
